# Generated by Django 3.1.7 on 2021-05-25 22:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateField(default=datetime.date.today)),
                ('confirmed', models.BooleanField(default=False)),
                ('amount', models.FloatField(default=0.0)),
                ('title', models.CharField(max_length=50)),
                ('details', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
    ]
