# Generated by Django 3.1.7 on 2021-07-25 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='subtitle',
            field=models.CharField(default='generic', max_length=50),
        ),
    ]
