# Generated by Django 3.1.7 on 2021-08-23 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('type_of_product', models.CharField(max_length=50)),
                ('details', models.CharField(max_length=50)),
                ('billing_type', models.CharField(max_length=50)),
                ('price', models.FloatField()),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
